The adapter should support SampledFunctionParameterType to arrays mapping/transfer #62
RHEAGROUP/DEH-ECOSIMPRO pull request #89
Opened 2021-09-30 16:50 UTC by arielleatrhea

Created a VariableRowVariable that represents a collection of variable ;  Update the MappedElementDefinitionRowViewModel so it can store mapping of arrays ;  Updates the Mapping configuration dialog ; Allow mapping only dimensional compatible parameter ;  Saving the mapping ;  Ensuring that the loading of saved mapping works with mapping that maps SFPT to OPC Arrays ; Tests

fixes #62 

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/pulls) open
- [x] I have verified that I am following the DEHP-EcosimPro [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEHP-ECOSIMPRO/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
- [x]  Create a VariableRowVariable that represents a collection of variable.
- [x] Update the MappedElementDefinitionRowViewModel so it can store mapping of arrays ?
- [x] Updates the Mapping configuration dialog
- [x] Allow mapping only dimensional compatible parameter
- [x]  Saving the mapping
- [x]  Ensuring that the loading of saved mapping works with mapping that maps SFPT to OPC Arrays
- [x]  Tests

2021-10-01 08:47 UTC, alexatrhea requested changes

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +        /// </summary>
No docs for all the fields below

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +        public ChooseMappingColumnsViewModel ListOfRowsToMap { get; set; } = new ChooseMappingColumnsViewModel();
Variable name says List but this is a viewmodel.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +        private IStatusBarControlViewModel statusBar;
No docs

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            IDstController dstController, IStatusBarControlViewModel statusBar, IMappingConfigurationService mappingService, INavigationService navigation) :
`mappingService` and `navigation` missing docs. Also `navigation` should be `navigationService`

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +                    //not compatible, show error to user
???

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            //foreach (var thing in this.ElementDefinitions.SelectMany(x => x.Parameter))
Delete commented code.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +                            this.AreVariableTypesAreCompatible();
Double `Are` in the name.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            var arrayVariables = availableVariables.Where(x => x.Reference.DisplayName.Text.Contains("[")).ToList();
Is there no better way to detect arrays?

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            var grouby = arrayVariables.GroupBy(x => this.GetNameFromArrayReference(x.Reference));
Bad variable name.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +        /// </summary>
No docs

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +        /// <param name="reference"></param>
No docs

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +        ///
no docs

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            var columnsOfParameter = parameter.ParameterType.NumberOfValues;
I dont think this is correct. `NumberOfValues` will not give you number of columns of a SampledFunction. Please unit test this method thoroughly with a large number of test cases for different sizes (i.e. 1x1 , 1 x m, n x 1, a few m x n, n x n )

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            var rowsAndColumnsOfVariable = variable.ActualValue.ToString().Split('[', 'x', ']');
This is not the right way to determine sizes. You have to look at the actual underlying model elements.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            string rowsOfVariable = "", columnsOfVariable = "";
we always declare `var`.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            bool areRowsCompatibles = false ;
same here. use `var`

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +        ///
no docs.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            for (int i = 0; i < listOfVariableRowViewModel.Count(); i++)
Add new line before the `for`.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +
unnecessary new line

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +
unnecessary new line

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +        private void GetRowAndColumnNumberFromName(string name, out int rowNumber, out int colNumber)
It looks like there was another method above that was doing the same thing?

Either way, same question as before, is there no better way to find dimensions than from the string?

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +        public bool IsList { get; private set; }
no docs

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +        /// <returns></returns>
no docs

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingColumnsViewModel.cs
> +            var probableindex = argName.Split('[');
Again you are splitting strings, seems like you have done it in several places.

2021-10-01 08:47 UTC, alexatrhea commented on DEHPEcosimPro/Views/Dialogs/ChooseMappingColumns.xaml.cs
> +﻿using System;
Missing header

2021-10-01 09:25 UTC, nathanatrhea requested changes

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +        public readonly ReferenceDescription Reference;
Hides inherited Reference, also why a public field?

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +        /// <param name="key">indice of the array</param>
Is it really the indices of the array or the dimensions or something else?

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +        public bool IsList { get; private set; }
missing doc

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +        /// <returns></returns>
missing doc

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +            if (arrayName != null)
arrayName is never null, Select() return a IEnumerable<out T>

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +                    if (isArray != null && isArray.Length == 1)
Can be simplified

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ArrayVariableRowViewModel.cs
> +                row.Name = this.GetDimension();
Multi calls on the same code

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingColumnsViewModel.cs
> +
extra space

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingColumnsViewModel.cs
> +            this.ParameterName = ModelCode(parameter);
missing this, also why not using the Methods from the type itself:  parameter.ModelCode();

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingColumnsViewModel.cs
> +        /// Name of the variable to map to
misplaced doc

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingColumnsViewModel.cs
> +        public ICloseWindowBehavior CloseWindowBehavior { get; set; }
unused reference

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingColumnsViewModel.cs
> +
extra line

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingColumnsViewModel.cs
> +        private string ModelCode(ParameterOrOverrideBase parameter)
is it really needed?

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingColumnsViewModel.cs
> +namespace DEHPEcosimPro.ViewModel.Rows
Doesn't look like the right namespace for this dialog view model

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ChooseMappingRowsViewModel.cs
> +            if (list.FirstOrDefault().Name.Contains('['))
possible null reference exception

2021-10-01 09:25 UTC, nathanatrhea commented on DEHPEcosimPro/ViewModel/Rows/ValueSetsToTableViewModel.cs
> +        public ValueSetsToTableViewModel(ParameterOrOverrideBase parameter, Option SelectedOption, ActualFiniteState SelectedState)
lower casing for parameter names

2021-10-04 13:20 UTC, arielleatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +            validationResult.Message = string.Empty;
corrected

2021-10-04 13:20 UTC, arielleatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +                    //not compatible, show error to user
used statusbar to avert the user

2021-10-04 13:21 UTC, arielleatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +                validationResult.ResultKind = userSelectecValue == true && areArraysCompatible
not in the case where rows are different (i did unit test)

2021-10-04 13:22 UTC, arielleatrhea commented on DEHPEcosimPro/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
>                  case IRowViewModelBase<ElementDefinition> elementDefinition:
i have to do more test to be sure

2021-11-10 22:03 UTC, merged