Sorting columns (Actual and Initial value) issues solved; fixes #92
RHEAGROUP/DEH-ECOSIMPRO pull request #97
Opened 2022-01-13 13:40 UTC by antoineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/pulls) open
- [x] I have verified that I am following the DEHP-EcosimPro [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEHP-ECOSIMPRO/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fixes #92 
* Add the conversion to double when the data.Value was an int
* The conversion solve the null value of certain averaged value
* On OPC array rows, moved the dimensions of the array to the name

2022-01-13 15:11 UTC, alexatrhea requested changes
Unless I'm mistaken you should be able to handle more than just doubles.

2022-01-14 10:44 UTC, alexatrhea requested changes
Few small changes requested, Good approach with the Behavior!

2022-01-14 10:44 UTC, alexatrhea commented on DEHPEcosimPro/Behaviors/TreeListSortingBehavior.cs
> +    public class TreeListSortingBehavior: Behavior<TreeListView>
comments missing

2022-01-14 10:44 UTC, alexatrhea commented on DEHPEcosimPro.Tests/Behaviors/TreeListSortingBehaviorTestFixture.cs
> +//    Author: Sam Gerené, Alex Vorobiev, Alexander van Delft, Nathanael Smiechowski.
Please add your name to the headers

2022-01-14 10:44 UTC, alexatrhea commented on DEHPEcosimPro/Behaviors/TreeListSortingBehavior.cs
> +            IComparable value1 = e.Value1 as IComparable;
in this entire method you should use `var` instead of explicit declaration.

2022-01-14 10:44 UTC, alexatrhea commented
Also seems that coverage is not there yet.

2022-01-14 10:56 UTC, samatrhea approved these changes
looks good to me!

2022-01-14 11:06 UTC, alexatrhea approved these changes
Approved

2022-01-14 11:07 UTC, nathanatrhea approved these changes

2022-01-14 11:09 UTC, merged